name: sagemaker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - boto3
  - sagemaker
  - pytorch
  - torchvision
  - pillow
  - tqdm
  - pip
  - pip:
    - smdebug